### PR TITLE
Fix formatting of negative durations

### LINKED ISSUE #259: Fix formatting of negative and overflowing durations
### Steps to reproduce

Formatting of durations with negative components error or output nonsensical values. Some examples:

```
iex(1)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: -1, seconds: 0, microseconds: 0})
"PT-1000000S"
iex(2)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: -1, seconds: -1, microseconds: 0})
"PT-1000001S"
iex(3)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: -1, seconds: -1, microseconds: -1})
** (FunctionClauseError) no function clause matching in Timex.Format.Duration.Formatters.Default.get_fractional_seconds/3
    (timex) lib/format/duration/formatters/default.ex:93: Timex.Format.Duration.Formatters.Default.get_fractional_seconds(-1000001, -1, [])
    (timex) lib/format/duration/formatters/default.ex:51: Timex.Format.Duration.Formatters.Default.lformat/2
iex(4)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: 1, seconds: 1, microseconds: -1})
** (FunctionClauseError) no function clause matching in Timex.Format.Duration.Formatters.Default.get_fractional_seconds/3
    (timex) lib/format/duration/formatters/default.ex:93: Timex.Format.Duration.Formatters.Default.get_fractional_seconds(40, -1, [minutes: 46, hours: 13, days: 11])
    (timex) lib/format/duration/formatters/default.ex:51: Timex.Format.Duration.Formatters.Default.lformat/2
```

There is also at least one other buggy case in this function not involving negative numbers:
```
iex(1)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: 0, seconds: 1, microseconds: 1000000})
"PT3.0S"
```
(I'd expect `"PT2.0S"` or `"PT2S"`)
**NOTE: The above example when microseconds exceeds 1000000 has been fixed by https://github.com/bitwalker/timex/pull/260**

### Description of issue

I am not entirely sure what the expected output would be in these cases, but it definitely shouldn't be throwing an error. @bitwalker might be able to provide more guidance on what the expected output looks like.

### PR DESCRIPTION
**Pull request by slavakisel**
### Summary of changes

fixes #259 

### Checklist

- [x] New functions have typespecs, changed functions were updated
- [x] Same for documentation, including moduledocs
- [x] Tests were added or updated to cover changes
- [x] Commits were squashed into a single coherent commit

### CODE REVIEW

File: lib/format/duration/formatters/default.ex [hunk 1]
```diff
@@ -80,11 +82,13 @@ defmodule Timex.Format.Duration.Formatters.Default do
   defp format_component({:minutes, m}, str), do: str <> "#{m}M"
   defp format_component({:seconds, s}, str), do: str <> "#{s}S"
 
-  defp deconstruct(%Duration{microseconds: micro} = duration),
-    do: deconstruct({Duration.to_seconds(duration, truncate: true), rem(micro, 1_000_000)}, [])
+  defp deconstruct(duration) do
+    micros = Duration.to_microseconds(duration) |> abs
```
Comment (slavakisel) [inline lib/format/duration/formatters/default.ex]: I switched to microseconds here because there was a bug with formatting of durations that had positive seconds and negative micros or vice versa. For instance, in previous implementation `Duration.from_erl({0, -2, 1_100_000})` was formatted as `PT0.1S` rather than `PT0.9S`. I added a [corresponding test](https://github.com/bitwalker/timex/pull/265/files#diff-0ff0a1e5c7cc6ecb09879df8a6b3fdadR16) for this case

File: lib/format/duration/formatters/default.ex [hunk 2]
```diff
@@ -94,15 +98,12 @@ defmodule Timex.Format.Duration.Formatters.Default do
...
-  defp deconstruct({seconds, us}, components),
-    do: get_fractional_seconds(seconds, us, components)
 
   defp get_fractional_seconds(seconds, 0, components),
     do: deconstruct({0, 0}, [{:seconds, seconds} | components])
-  defp get_fractional_seconds(seconds, micro, components) when micro > 0 do
+  defp get_fractional_seconds(seconds, micro, components) do
     millis = micro
     |> Duration.from_microseconds
-    |> Duration.abs
```
Comment (slavakisel) [inline lib/format/duration/formatters/default.ex]: since micro is always positive now (see line 86) this check can be removed

File: test/format_duration_default_test.exs [hunk 3]
```diff
@@ -1,4 +1,19 @@
...
+  alias Timex.Format.Duration.Formatters
+
+  doctest Formatters.Default
+
+  defp format(megaseconds, seconds, microseconds) do
+    Duration.from_erl({megaseconds, seconds, microseconds})
+      |> Formatters.Default.format
+  end
+
+  test "format negative duration" do
```
Comment (slavakisel) [inline test/format_duration_default_test.exs]: I decided to keep all other tests here to avoid documentation overload with examples

**Comment by bitwalker** [comment]
Looks good to me! Thanks for the PR!
